### PR TITLE
let `ErsatzServer` implement `Closable`

### PR DESCRIPTION
**Pull request by musketyr**
to be able to use `@AutoCleanup` without specifying the close method name

### CODE REVIEW

**Comment by cjstehno** [comment]
Thanks. Not sure why I never thought of that. ;-)

**Comment by cjstehno** [comment]
Can you merge this into the `development` branch instead, please.

**Comment by musketyr** [comment]
it looks weird now. can @cjstehno maybe can you cherry pick instead? the changes are trivial

**Comment by cjstehno** [comment]
Sure. I am going to change my branch management strategy with this release too. :-)

**Comment by cjstehno** [comment]
I have patched this into the 1.7.0 release code. Thanks.

**Comment by musketyr** [comment]
Thank you as well

Dne ne 15. čvc 2018 18:17 uživatel Christopher J. Stehno <
notifications@github.com> napsal:

**Pull request closed without merging**
