### PR TITLE
Fixes #56 - binary compatibility with Undertow 1.3.x

### LINKED ISSUE #56: binary compatibility with Undertow 1.3.x
If not really necessary it would be nice if Ersatz server is compatible with Undertow 1.3.x (namely 1.3.15.Final) which is used by various spring boot related libraries (https://mvnrepository.com/artifact/io.undertow/undertow-core/1.3.25.Final/usages). This disqualifies from using Ersatz with Spring Boot or Grails 3. The construct offending the compatibility is currently `server.listenerInfo`:

```
            actualHttpPort = (server.listenerInfo[0].address as InetSocketAddress).port

            if (httpsEnabled) {
                actualHttpsPort = (server.listenerInfo[1].address as InetSocketAddress).port
            }
```

### PR DESCRIPTION
**Pull request by musketyr**

### CODE REVIEW

**Comment by cjstehno** [comment]
Hmm... I don't really like the system property injection to determine the version being used. My understanding is that the way I get the actual port is not supported in 1.3, but only 1.4? I don't think there is any real reason I cannot just backdate the library I use to 1.3 but I will have to make sure I am not losing any features.

I wonder if the gradle fuzzy version range support would help here combined with with your fix... just look for `1.3+` - not sure if that would take what you have or still just download the latest available.

Have to think about this one for a bit. Is this a showstopper for you?

**Comment by cjstehno** [comment]
Also, thanks for the pull request!

**Comment by musketyr** [comment]
Yes, this was a show stopper for me. I had to use Undertow directly 😞 I'm cool with the other solution you've suggested so I'm closing this one in favour of the simpler solution (downgrade to 1.3.15 of the whole library).

**Comment by cjstehno** [comment]
I will cut a release with this fix today.

**Comment by musketyr** [comment]
Fantastic!

**Comment by cjstehno** [comment]
I just woke up so it will be a few hours ;-)

**Pull request closed without merging**
